Repository Rudy-Menjivar/confessions, pull requests merged in 2021-03, with the labels that each got.

#1 applied project information with contributing guidelines
  README.md
Labels: documentation

#2 Added new team member
  README.md
Labels: documentation

#3 added starter code
  .gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/registerServiceWorker.js
  package.json
  server.js
Labels: good first issue

#10 Footer
  client/src/components/Footer/index.js
  client/src/components/Footer/style.css
Labels: enhancement

#60 user password is now hashed with bcrypt
  models/user.js
Labels: enhancement
